#!/usr/bin/env bash
# ==============================================================================
# Multi-Identity & Environment Generator (Git, GitHub CLI, mise, Azure, DBX, AWS)
# ==============================================================================
# Generates isolated developer environments per workspace:
#   1. Git: ~/.gitconfig.local with includeIf "gitdir:..." mappings
#   2. GitHub CLI: Isolated ~/.config/gh-<profile>/ configs (GH_CONFIG_DIR)
#   3. mise: Workspace root .mise.toml (Databricks, Azure CLI, AWS, GH)
#   4. Azure CLI: Isolated ~/.azure-<profile>/ state directories
#   5. Shell Hooks: Fish & Zsh directory-based auto-switching fallback
#
# Keeps your public dotfiles repository 100% sanitized without company names.
#
# Usage:
#   ./setup_profiles.sh
# Config location:
#   ~/.config/profiles.conf (untracked local file)
# ==============================================================================

set -e

CONF_FILE="${HOME}/.config/profiles.conf"
FISH_SWITCH="${HOME}/.config/fish/conf.d/gh_switch.fish"
ZSH_LOCAL="${HOME}/.zshrc.local"
GITCONFIG_LOCAL="${HOME}/.gitconfig.local"

mkdir -p "${HOME}/.config"

# 1. Create generic template if none exists
if [ ! -f "$CONF_FILE" ]; then
  cat << 'CONF_EOF' > "$CONF_FILE"
# Multi-Identity Profile Mappings
# Format: folder_pattern | profile | git_email | ssh_key | gh_user | dbx_profile | azure_profile | aws_profile
#
# Examples:
# projects/work-alpha* | alpha    | dev@alpha.example.com | ~/.ssh/id_alpha    | dev-alpha | alpha-qas | alpha | alpha-dev
# projects/work-beta*  | beta     | dev@beta.example.com  | ~/.ssh/id_beta     | dev-beta  | beta-prd  | beta  |
# *                    | personal | user@example.com      | ~/.ssh/id_personal | user-main |           |       |
CONF_EOF
  echo "Created template configuration at: $CONF_FILE"
  echo "Please customize $CONF_FILE and rerun this script."
  exit 0
fi

echo "Reading profile definitions from: $CONF_FILE"

# 2. Parse configuration file
declare -a RULES=()
DEFAULT_PROFILE="personal"
DEFAULT_EMAIL=""
DEFAULT_SSH_KEY=""
DEFAULT_GH_USER=""

GITCONFIG_RULES_TMP=$(mktemp)

while IFS='|' read -r pattern profile email ssh_key gh_user dbx_profile azure_profile aws_profile || [ -n "$pattern" ]; do
  [[ "$pattern" =~ ^[[:space:]]*# ]] && continue
  [[ -z "$pattern" ]] && continue

  pattern=$(echo "$pattern" | xargs)
  profile=$(echo "$profile" | xargs)
  email=$(echo "$email" | xargs)
  ssh_key=$(echo "$ssh_key" | xargs)
  gh_user=$(echo "$gh_user" | xargs)
  dbx_profile=$(echo "$dbx_profile" | xargs)
  azure_profile=$(echo "$azure_profile" | xargs)
  aws_profile=$(echo "$aws_profile" | xargs)

  # Expand tilde in ssh_key if present
  ssh_key="${ssh_key/#\~/$HOME}"

  # --- A. Git Profile Setup ---
  target_gitconfig="${HOME}/.gitconfig-${profile}.local"
  cat << GIT_EOF > "$target_gitconfig"
[user]
	email = $email
GIT_EOF
  if [ -n "$ssh_key" ] && [ -f "$ssh_key" ]; then
    cat << SSH_EOF >> "$target_gitconfig"
[core]
	sshCommand = ssh -i $ssh_key -o IdentitiesOnly=yes
SSH_EOF
  fi

  # --- B. GitHub CLI Profile Setup ---
  target_gh_dir="${HOME}/.config/gh-${profile}"
  mkdir -p "$target_gh_dir"
  if [ -f "${HOME}/.config/gh/config.yml" ] && [ ! -f "${target_gh_dir}/config.yml" ]; then
    cp "${HOME}/.config/gh/config.yml" "${target_gh_dir}/"
  fi
  if [ -f "${HOME}/.config/gh/hosts.yml" ] && [ ! -f "${target_gh_dir}/hosts.yml" ]; then
    cp "${HOME}/.config/gh/hosts.yml" "${target_gh_dir}/"
  fi
  if [ -n "$gh_user" ] && [ -f "${target_gh_dir}/hosts.yml" ]; then
    GH_CONFIG_DIR="$target_gh_dir" gh auth switch --hostname github.com --user "$gh_user" >/dev/null 2>&1 || true
  fi

  # --- C. Azure CLI State Directory Setup ---
  if [ -n "$azure_profile" ]; then
    target_azure_dir="${HOME}/.azure-${azure_profile}"
    mkdir -p "$target_azure_dir"
    if [ -d "${HOME}/.azure" ] && [ -z "$(ls -A "$target_azure_dir" 2>/dev/null)" ]; then
      cp -R "${HOME}/.azure/"* "$target_azure_dir/" 2>/dev/null || true
    fi
  fi

  # --- D. mise .mise.toml per Workspace ---
  clean_dir="${pattern%\*}"
  clean_dir="${clean_dir%/}"
  workspace_path="${HOME}/${clean_dir}"

  if [ "$pattern" != "*" ] && [ "$pattern" != "default" ] && [ -d "$workspace_path" ]; then
    mise_file="${workspace_path}/.mise.toml"
    cat << MISE_EOF > "$mise_file"
# Environment configuration for $profile (auto-generated by dotfiles/git/setup_profiles.sh)
[env]
GH_CONFIG_DIR = "{{env.HOME}}/.config/gh-${profile}"
MISE_EOF

    if [ -n "$dbx_profile" ]; then
      echo "DATABRICKS_CONFIG_PROFILE = \"$dbx_profile\"" >> "$mise_file"
    fi
    if [ -n "$azure_profile" ]; then
      echo "AZURE_CONFIG_DIR = \"{{env.HOME}}/.azure-${azure_profile}\"" >> "$mise_file"
    fi
    if [ -n "$aws_profile" ]; then
      echo "AWS_PROFILE = \"$aws_profile\"" >> "$mise_file"
    fi

    if command -v mise &> /dev/null; then
      mise trust "$mise_file" >/dev/null 2>&1 || true
    fi
  fi

  if [ "$pattern" = "*" ] || [ "$pattern" = "default" ]; then
    DEFAULT_PROFILE="$profile"
    DEFAULT_EMAIL="$email"
    DEFAULT_SSH_KEY="$ssh_key"
    DEFAULT_GH_USER="$gh_user"
  else
    RULES+=("$pattern|$profile")
    cat << INC_EOF >> "$GITCONFIG_RULES_TMP"

[includeIf "gitdir:~/$clean_dir/"]
    path = ~/.gitconfig-${profile}.local
INC_EOF
  fi
done < "$CONF_FILE"

# --- 3. Write ~/.gitconfig.local ---
cat << MAIN_GIT_EOF > "$GITCONFIG_LOCAL"
# Auto-generated by dotfiles/git/setup_profiles.sh
[user]
	email = $DEFAULT_EMAIL
MAIN_GIT_EOF

cat "$GITCONFIG_RULES_TMP" >> "$GITCONFIG_LOCAL"
rm "$GITCONFIG_RULES_TMP"
echo "✓ Updated Git local config: $GITCONFIG_LOCAL"

# --- 4. Generate Fish Hook (~/.config/fish/conf.d/gh_switch.fish) ---
mkdir -p "$(dirname "$FISH_SWITCH")"
cat << 'FISH_HEADER' > "$FISH_SWITCH"
# Auto-generated by dotfiles/git/setup_profiles.sh
function __gh_auto_switch --on-variable PWD --description "Isolate GitHub config based on directory"
FISH_HEADER

FIRST=true
for rule in "${RULES[@]}"; do
  IFS='|' read -r pattern profile <<< "$rule"
  if [ "$FIRST" = true ]; then
    echo "    if string match -qi \"\$HOME/$pattern\" \"\$PWD\"" >> "$FISH_SWITCH"
    FIRST=false
  else
    echo "    else if string match -qi \"\$HOME/$pattern\" \"\$PWD\"" >> "$FISH_SWITCH"
  fi
  echo "        set -gx GH_CONFIG_DIR \"\$HOME/.config/gh-$profile\"" >> "$FISH_SWITCH"
done

if [ "$FIRST" = false ]; then
  echo "    else" >> "$FISH_SWITCH"
  echo "        set -gx GH_CONFIG_DIR \"\$HOME/.config/gh-$DEFAULT_PROFILE\"" >> "$FISH_SWITCH"
  echo "    end" >> "$FISH_SWITCH"
else
  echo "    set -gx GH_CONFIG_DIR \"\$HOME/.config/gh-$DEFAULT_PROFILE\"" >> "$FISH_SWITCH"
fi

cat << 'FISH_FOOTER' >> "$FISH_SWITCH"
end

if status is-interactive
    __gh_auto_switch
end
FISH_FOOTER
echo "✓ Updated Fish switch hook: $FISH_SWITCH"

# --- 5. Generate Zsh Snippet in ~/.zshrc.local ---
ZSH_TMP=$(mktemp)
cat << 'ZSH_HEADER' > "$ZSH_TMP"
# GitHub CLI directory-based profile isolation (generated by dotfiles/git/setup_profiles.sh)
autoload -Uz add-zsh-hook

__gh_auto_switch() {
    local current_pwd="${PWD:l}"
ZSH_HEADER

FIRST=true
for rule in "${RULES[@]}"; do
  IFS='|' read -r pattern profile <<< "$rule"
  pattern_lower=$(echo "$pattern" | tr '[:upper:]' '[:lower:]')
  if [ "$FIRST" = true ]; then
    echo "    if [[ \"\$current_pwd\" == \"\${HOME:l}/$pattern_lower\"* ]]; then" >> "$ZSH_TMP"
    FIRST=false
  else
    echo "    elif [[ \"\$current_pwd\" == \"\${HOME:l}/$pattern_lower\"* ]]; then" >> "$ZSH_TMP"
  fi
  echo "        export GH_CONFIG_DIR=\"\$HOME/.config/gh-$profile\"" >> "$ZSH_TMP"
done

if [ "$FIRST" = false ]; then
  echo "    else" >> "$ZSH_TMP"
  echo "        export GH_CONFIG_DIR=\"\$HOME/.config/gh-$DEFAULT_PROFILE\"" >> "$ZSH_TMP"
  echo "    fi" >> "$ZSH_TMP"
else
  echo "    export GH_CONFIG_DIR=\"\$HOME/.config/gh-$DEFAULT_PROFILE\"" >> "$ZSH_TMP"
fi

cat << 'ZSH_FOOTER' >> "$ZSH_TMP"
}

add-zsh-hook chpwd __gh_auto_switch
__gh_auto_switch
ZSH_FOOTER

touch "$ZSH_LOCAL"
sed -i '' '/# GitHub CLI directory-based profile isolation/,+35d' "$ZSH_LOCAL" 2>/dev/null || true
cat "$ZSH_TMP" >> "$ZSH_LOCAL"
rm "$ZSH_TMP"
echo "✓ Updated Zsh switch hook: $ZSH_LOCAL"

echo "=== Profile generation complete for Git, GitHub CLI, mise, Azure & Databricks ==="
